services:
  - type: web
    name: Cours-de-Cloud
    region: frankfurt  
    plan: free
    runtime: docker
    envVars:
      - key: DB_NAME
        fromDatabase:
          name: mydb
          property: connectionString

databases:
  - name: mydb
    databaseName: mydbName
    user: myuser
    region: frankfurt
    plan: free