services:
  - type: web
    name: Cours-de-Cloud
    region: frankfurt  
    plan: free
    runtime: docker
    envVars:
      - key: DB_NAME
        fromDatabase:
          name: DB_NAME
          property: connectionString

  databases:
    - name: mydb
      region: frankfurt
      plan: free
      databaseName: mydbName # optional (Render may add a suffix)