services:
  - type: web
    name: myweb
    region: frankfurt  
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASEURL
        fromDatabase:
          name: mydb
          property: connectionString

databases:
  - name: mydb
    databaseName: mydbname
    user: myuser
    region: frankfurt
    plan: free